language: node
node_js:
  - stable
  - lts/*
env:
  - WEBPACK_VERSION=4.4.0 PLUGIN_VERSION=1.0.0
install:
  - npm install --ignore-scripts
  - npm rm webpack
  - npm rm webpack-manifest-replace-plugin
  - npm install webpack@WEBPACK_VERSION webpack-manifest-replace-plugin@PLUGIN_VERSION --ignore-scripts || true
script:
  - npm test

