language: node_js
node_js:
  - stable
  - lts/*
env:
  - WEBPACK_VERSION=4.4.0
install:
  - npm install --ignore-scripts
  - npm rm webpack
  - npm install webpack@$WEBPACK_VERSION --ignore-scripts
  - npm run build
script:
  - npm test

